#!/bin/sh
mount -a
mkdir -p /var/run
mkdir -p /var/log

# set system hostname
sysctl -w kernel.hostname=`nvram_get HostName`
echo "`nvram_get HostName`" > /etc/hostname

cat /etc_ro/motd

# start init scripts
for i in /etc_ro/init/*.sh; do
    if [ -r $i ]; then
        . $i
    fi
done

. /etc/profile

#nvram_daemon&
#goahead&

#for telnet debugging
#telnetd

#for syslogd

#/sbin/internet.sh
#/sbin/ntp.sh
