#!/bin/sh
mount -a
mkdir -p /var/run
mkdir -p /var/log

# set system hostname
sysctl -w kernel.hostname=`nvram_get HostName`
echo "`nvram_get HostName`" > /etc/hostname

cat /etc_ro/motd

#run syslogd
syslogd

# run klogd
klogd

# start init scripts
for i in /etc_ro/init/*.sh; do
    if [ -r $i ]; then
        echo "------------------- START ------------------"
        echo $i
        echo "--------------------------------------------"
        . $i
    fi
done

. /etc/profile

#goahead&
#/sbin/internet.sh
#/sbin/ntp.sh
